Repository codeit-part3-team5/whyne, pull requests merged in 2025-06, with the labels that each got.

#11 [Chore/5] :🔧 prettier 설정
  .prettierrc
  .vscode/settings.json
Labels: ⚙️Setting

#13 [Docs/10] : 📝 [REAME.md 생성]
  .github/PULL_REQUEST_TEMPLATE/bugfix_template.md
  .github/pull_request_template.md
  README.md
Labels: 📝Docs, ⚙️Setting

#15 [Chore/14] :🔧 ESLint 설정 수정 및 Husky 설정
  .eslintrc.json
  .husky/pre-commit
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: ⚙️Setting

#19 🔧[Chore/16] : 디렉토리 구조 설정 및 tailwind설정
  .eslintcache
  .prettierrc
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  src/api/.gitkeep
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/.gitkeep
  src/constants/.gitkeep
  src/fonts/PretendardVariable.woff2
  src/hooks/.gitkeep
  src/lib/.gitkeep
  src/models/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  tailwind.config.js
  tsconfig.json
Labels: ⚙️Setting

#27 ✨ [Feature/22] 버튼 컴포넌트 제작
  .eslintcache
  .gitignore
  src/app/globals.css
  src/assets/google-icon.svg
  src/assets/kakao-icon.svg
  src/components/Button.tsx
  src/components/Spinner.tsx
  src/constants/.gitkeep
  src/constants/buttonStyles.ts
Labels: ✨Feature

#28 🔧 [Chore/18] axios 토큰 설정 기능 및 로그인 더미 페이지 추가
  package.json
  pnpm-lock.yaml
  src/apis/axios/axiosConfig.ts
  src/apis/index.d.ts
  src/apis/usersApi.ts
  src/components/Login/Login.tsx
Labels: ⚙️Setting

#29 ✨ [Feature/21] 와인카드 제작
  .eslintrc
  package.json
  pnpm-lock.yaml
  src/app/wines/[id]/page.tsx
  src/app/wines/page.tsx
  src/components/about-wine/WineCard.tsx
Labels: ✨Feature

#34 ✨[Feature/30] 공통 컴포넌트 드롭다운, 와인타입 인풋 제작
  src/api/.gitkeep
  src/app/wines/page.tsx
  src/assets/dropdown-icon.png
  src/components/.gitkeep
  src/components/DropDown.tsx
  src/components/WineTypeDropDown.tsx
  src/constants/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
Labels: ✨Feature

#35 ✨[Feature/24] 모달 컴포넌트 제작
  src/app/globals.css
  src/app/layout.tsx
  src/app/test/TestContent.tsx
  src/app/test/page.tsx
  src/assets/close-icon.svg
  src/assets/star-icon.svg
  src/components/modal/Modal.tsx
  src/components/modal/modalClassNames.ts
  src/store/useModalStore.ts
Labels: ✨Feature

#41 ✨ [Feature/32] 푸터 컴포넌트 제작
  public/images/github.png
  src/components/Footer/Footer.tsx
Labels: ✨Feature

#43 ✨[Feature/36] 이달의 추천와인 컴포넌트 개발
  src/app/wines/page.tsx
  src/assets/icons/star-icon.svg
  src/assets/left-button-icon.png
  src/assets/right-botton-icon.png
  src/components/about-wine/MiniWineCard.tsx
  src/components/about-wine/MonthlyWines.tsx
  src/components/about-wine/RatingScore.tsx
  src/components/about-wine/WineCard.tsx
  src/components/about-wine/WineTypeDropDown.tsx
Labels: ✨Feature

#45 ✨[Feature/44] 컴포넌트 반응형 디자인 적용
  src/app/globals.css
  src/app/page.tsx
  src/app/wines/page.tsx
  src/assets/star-icon.svg
  src/components/DropDown.tsx
  src/components/about-wine/MiniWineCard.tsx
  src/components/about-wine/MonthlyWines.tsx
  src/components/about-wine/RatingScore.tsx
  src/components/about-wine/WineCard.tsx
  src/components/about-wine/WineTypeDropDown.tsx
  src/constants/buttonStyles.ts
  src/hooks/.gitkeep
  src/styles/.gitkeep
Labels: ✨Feature

#47 ✨[Feature/37] 리뷰 목록 컴포넌트 구현
  .coderabbit.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/test/TestContent.tsx
  src/app/test/page.tsx
  src/app/wines/[id]/page.tsx
  src/assets/ellipse-icon.svg
  src/assets/icons/star-icon.svg
  src/assets/star-icon.svg
  src/components/Arrow.tsx
  src/components/DropDown.tsx
  src/components/Footer/Footer.tsx
  src/components/Heart.tsx
  src/components/Star.tsx
  src/components/WineTaste.css
  src/components/WineTaste.tsx
  src/components/modal/Modal.tsx
  src/components/profile/ProfileCircle.tsx
  src/components/wine-detail/Review/AromaItem.tsx
  src/components/wine-detail/Review/LikeButton.tsx
  src/components/wine-detail/Review/Rating.tsx
  src/components/wine-detail/Review/ReviewBottomSection.tsx
  src/components/wine-detail/Review/ReviewItem.tsx
  src/components/wine-detail/Review/ReviewList.tsx
  src/components/wine-detail/Review/ReviewMiddleSection.tsx
  src/components/wine-detail/Review/ReviewTopSection.tsx
  src/components/wine-detail/Review/UserInfo.tsx
  src/components/wine-detail/Review/WineTaste.tsx
  src/constants/wineTaste.ts
  src/hooks/useMediaQuery.ts
  src/mocks/winesDetail.json
  src/utils/.gitkeep
  src/utils/aromaConverter.ts
  src/utils/timeForToday.ts
  tsconfig.json
Labels: ✨Feature

#54 ✨ [Feature/40] 프로필 페이지의 내가 작성한 리뷰 탭 구현
  src/app/profile/layout.tsx
  src/app/profile/page.tsx
  src/assets/base-profile.svg
  src/assets/camera-icon.svg
  src/assets/ellipse-icon.svg
  src/assets/eye-password-hide.svg
  src/assets/eye-password-show.svg
  src/assets/search-icon.svg
  src/components/input/FileInput.tsx
  src/components/input/PasswordInput.tsx
  src/components/input/SearchInput.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/ProfileTabs.tsx
  src/components/profile/ReviewCard.tsx
  src/components/wine-detail/Review/ReviewTopSection.tsx
  src/mocks/reviewsData.json
Labels: ✨Feature

#56 ✨[Feature] 리뷰 개요 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/app/wines/[id]/page.tsx
  src/components/ReviewSummary.tsx
  src/components/profile/ReviewCard.tsx
  src/components/wine-detail/review-list/AromaItem.tsx
  src/components/wine-detail/review-list/LikeButton.tsx
  src/components/wine-detail/review-list/Rating.tsx
  src/components/wine-detail/review-list/ReviewBottomSection.tsx
  src/components/wine-detail/review-list/ReviewItem.tsx
  src/components/wine-detail/review-list/ReviewList.tsx
  src/components/wine-detail/review-list/ReviewMiddleSection.tsx
  src/components/wine-detail/review-list/ReviewTopSection.tsx
  src/components/wine-detail/review-list/UserInfo.tsx
  src/components/wine-detail/review-list/WineTaste.tsx
  src/components/wine-detail/review-overview/RatingProgress.css
  src/components/wine-detail/review-overview/RatingProgress.tsx
  src/components/wine-detail/review-overview/ReviewOverview.tsx
  src/utils/reviewUtil.ts
Labels: ✨Feature

#57 [Feature/53] 필터 컴포넌트들 제작 / 와인등록하기, 필터 모달 제작
  public/images/.gitkeep
  src/app/globals.css
  src/app/wines/page.tsx
  src/assets/add-image.png
  src/assets/filter-icon.png
  src/components/Filters/PriceFilter.tsx
  src/components/Filters/RatingFilter.tsx
  src/components/Filters/TypeFilter.tsx
  src/components/about-wine/MiniWineCard.tsx
  src/components/about-wine/WineInfoCard.tsx
  src/components/about-wine/WineTypeDropDown.tsx
  src/components/modal/FilterModal.tsx
  src/components/modal/WinePostModal.tsx
Labels: ✨Feature, 💄 Design

#60 ✨ [Feature/59] 카카오톡 소셜 로그인 핵심 기능 개발
  next.config.js
  src/apis/authApi.ts
  src/apis/index.d.ts
  src/apis/oauthAppsApi.ts
  src/app/auth/kakao/page.tsx
  src/app/layout.tsx
  src/components/Login/KakaoSdkScript.tsx
  src/components/Login/Login.tsx
Labels: ✨Feature

#62 🐛 [Fix/61] useSearchParams 함수 빌드 에러 수정
  src/app/auth/kakao/KakaoRedirectPage.tsx
  src/app/auth/kakao/page.tsx
Labels: 🐛Bug Fix

#63 ✨ [Feature/55] 프로필 페이지의 내가 등록한 와인 UI 구현
  public/images/.gitkeep
  src/app/profile/page.tsx
  src/components/profile/BaseCard.tsx
  src/components/profile/MyReviewCard.tsx
  src/components/profile/MyWineCard.tsx
  src/components/profile/ProfileCircle.tsx
  src/components/profile/ProfileTabs.tsx
  src/components/profile/ReviewCard.tsx
  src/hooks/.gitkeep
  src/hooks/useDropdown.ts
  src/mocks/myReviewsData.json
  src/mocks/myWinesData.json
  src/types/.gitkeep
  src/types/ReviewList.ts
  src/types/User.ts
  src/types/Wine.ts
Labels: ✨Feature

#65 ✨ [Feature] 리뷰 남기기 모달 구현
  src/app/globals.css
  src/app/test/stars/page.tsx
  src/app/wines/[id]/page.tsx
  src/assets/wine-icon.svg
  src/components/CustomStar.tsx
  src/components/RatingStars.tsx
  src/components/WineTaste.tsx
  src/components/modal/Modal.tsx
  src/components/modal/modalClassNames.ts
  src/components/wine-detail/review-list/WineTaste.tsx
  src/components/wine-detail/review-modal/AromaSelector.tsx
  src/components/wine-detail/review-modal/ReviewMiddle.tsx
  src/components/wine-detail/review-modal/ReviewModal.tsx
  src/components/wine-detail/review-modal/ReviewTitle.tsx
  src/components/wine-detail/review-modal/ReviewTop.tsx
  src/components/wine-detail/review-modal/ReviewWrite.tsx
  src/components/wine-detail/review-overview/ReviewOverview.tsx
  src/store/useReviewStore.ts
  src/store/useWineStore.ts
  src/styles/buttonStyles.ts
Labels: ✨Feature

#68 ✨ [Feature/67] 로그인 페이지 UI 구현
  src/app/signin/page.tsx
  src/components/Login/Login.tsx
  src/components/Login/Signin.tsx
  src/components/Login/SigninForm.tsx
Labels: ✨Feature

#75 ✨ [Feature/69] 프로필 이미지, 프로필 정보 api 구현
  src/apis/imagesApi.ts
  src/apis/usersApi.ts
  src/components/input/FileInput.tsx
  src/components/profile/ProfileHeader.tsx
  src/hooks/useProfile.ts
  src/utils/fileUtil.ts
Labels: ✨Feature

#73 ✨ [Feature/64] 추가 기능들 및 반응형 코드 수정
  src/apis/oauthAppsApi.ts
  src/app/wines/page.tsx
  src/components/DropDown.tsx
  src/components/Filters/PriceFilter.tsx
  src/components/Filters/RatingFilter.tsx
  src/components/Filters/TypeFilter.tsx
  src/components/about-wine/MonthlyWines.tsx
  src/components/about-wine/WineInfoCard.tsx
  src/components/modal/FilterModal.tsx
Labels: ✨Feature, 💄 Design

#72 ✨ [Feature] 와인 상세 페이지 api 연동
  package.json
  pnpm-lock.yaml
  public/images/no-review.png
  src/api/.gitkeep
  src/apis/reviewsApi.ts
  src/apis/winesApi.ts
  src/app/layout.tsx
  src/app/test/token-setter/page.tsx
  src/app/wines/[id]/page.tsx
  src/components/ReviewSummary.tsx
  src/components/wine-detail/NoReviewSection.tsx
  src/lib/.gitkeep
Labels: ✨Feature

#76 ✨ [Feature/71] API 호출 실패 케이스 처리
  src/apis/authApi.ts
  src/apis/index.d.ts
  src/app/signup/page.tsx
  src/components/Login/SigninForm.tsx
  src/components/Login/SignupForm.tsx
Labels: ✨Feature

#80 ✨[Feature/74] 와인 목록 페이지 api 연결
  src/apis/winesApi.ts
  src/app/wines/page.tsx
  src/components/Filters/PriceFilter.tsx
  src/components/about-wine/MonthlyWines.tsx
  src/components/about-wine/WineTypeDropDown.tsx
  src/components/input/types.ts
  src/components/modal/FilterModal.tsx
  src/components/modal/WinePostModal.tsx
Labels: ✨Feature

#81 ✨ [Feature/78] 프로필 페이지 리뷰, 와인 목록 조회 api 연결
  src/apis/usersApi.ts
  src/app/layout.tsx
  src/app/profile/page.tsx
  src/components/profile/MyReviewCard.tsx
  src/components/profile/MyWineCard.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useMyReviews.ts
  src/hooks/useMyWines.ts
  src/hooks/usePagination.ts
Labels: ✨Feature

#79 ✨ [Feature] 리뷰 남기기 모달 api 연결
  src/apis/reviewsApi.ts
  src/app/wines/[id]/page.tsx
  src/components/RatingStars.tsx
  src/components/wine-detail/review-list/LikeButton.tsx
  src/components/wine-detail/review-list/Rating.tsx
  src/components/wine-detail/review-list/ReviewItem.tsx
  src/components/wine-detail/review-list/ReviewList.tsx
  src/components/wine-detail/review-list/ReviewTopSection.tsx
  src/components/wine-detail/review-modal/AromaSelector.tsx
  src/components/wine-detail/review-modal/ReviewModal.tsx
  src/components/wine-detail/review-modal/ReviewTitle.tsx
  src/components/wine-detail/review-modal/ReviewTop.tsx
  src/hooks/useAuth.ts
  src/store/useReviewStore.ts
  src/store/useWineStore.ts
  src/utils/tokenUtils.ts
Labels: ✨Feature

#88 🐛 [Fix/87] 헤더 로그인 상태 버그 수정 및 드롭다운 기능 추가
  src/apis/axios/axiosConfig.ts
  src/apis/winesApi.ts
  src/app/auth/kakao/KakaoRedirectPage.tsx
  src/app/wines/page.tsx
  src/components/Header/Header.tsx
  src/components/Header/ProfileDropDown.tsx
  src/components/Login/SigninForm.tsx
  src/components/Login/SignupForm.tsx
  src/components/Login/useLogin.tsx
Labels: 🐛Bug Fix

#86 🐛[Fix] 프로필 페이지에서 나온 버그 이슈
  src/app/profile/page.tsx
  src/hooks/useAuthGuard.ts
  src/hooks/useMyReviews.ts
  src/hooks/useMyWines.ts
  src/hooks/usePagination.ts
  src/hooks/useProfile.ts
  src/utils/validation.ts
Labels: 🐛Bug Fix

#89 ✨ [Feature] 와인 상세페이지 리뷰 삭제 구현
  src/apis/reviewsApi.ts
  src/components/DropDown.tsx
  src/components/delete-confirm-modal/DeleteConfirmModal.tsx
  src/components/wine-detail/review-list/ReviewTopSection.tsx
  src/styles/buttonStyles.ts
Labels: ✨Feature

#95 🐛 [Fix] 리뷰 모달 api 수정
  src/components/DropDown.tsx
  src/components/modal/Modal.tsx
  src/components/wine-detail/review-modal/ReviewModal.tsx
  src/hooks/useAuth.ts
Labels: 🐛Bug Fix

#99 🐛 [Fix]: 아로마 타입 수정
  src/types/Aroma.ts
  src/utils/aromaConverter.ts
Labels: 🐛Bug Fix

#93 ✨ [Feature/83] 테스트 결과 반영
  public/images/.gitkeep
  src/api/.gitkeep
  src/apis/winesApi.ts
  src/app/wines/page.tsx
  src/components/about-wine/MonthlyWines.tsx
  src/components/modal/FilterModal.tsx
  src/components/modal/WinePostModal.tsx
  src/hooks/useInfiniteScroll.ts
  src/lib/.gitkeep
Labels: ✨Feature, 💄 Design

#108 🐛 Fix: 프로필 와인/리뷰 목록 새로고침
  src/components/dropdown/ReviewDropDown.tsx
  src/components/dropdown/WineDropDown.tsx
  src/components/profile/BaseCard.tsx
  src/components/profile/MyReviewCard.tsx
  src/components/profile/MyWineCard.tsx
Labels: 🐛Bug Fix

#112 💄[UI] 모바일 반응형 단위 수정
  src/app/globals.css
Labels: enhancement, 💄 Design

#115 ✨ [Feature/114] 토큰 갱신 후 저장 및 프로필 이미지 업데이트 후 반영하기
  src/apis/axios/axiosConfig.ts
  src/app/auth/kakao/KakaoRedirectPage.tsx
  src/components/Header/Header.tsx
  src/components/Login/SigninForm.tsx
  src/components/Login/SignupForm.tsx
  src/components/Login/useLogin.tsx
  src/hooks/useProfile.ts
Labels: ✨Feature

#116 🐛 [Fix/113] 프로필 와인/리뷰 수정 후 새로고침
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Login/Signin.tsx
  src/components/Login/Signup.tsx
  src/components/about-wine/MiniWineCard.tsx
  src/components/about-wine/WineCard.tsx
  src/components/about-wine/WineInfoCard.tsx
  src/components/dropdown/ReviewDropDown.tsx
  src/components/dropdown/WineDropDown.tsx
  src/components/input/FileInput.tsx
  src/components/modal/WineEditModal.tsx
  src/components/modal/WinePostModal.tsx
  src/components/profile/MyWineCard.tsx
  src/components/profile/ProfileCircle.tsx
  src/components/wine-detail/review-modal/ReviewEditModal.tsx
Labels: 🐛Bug Fix

#118 ⚡️ [Fix] 로그아웃 시 와인 목록 페이지로 이동되도록 수정
  src/components/Header/ProfileDropDown.tsx
Labels: 🐛Bug Fix

#120 💄 Style: 로그인, 회원가입 상하 padding 추가
  src/app/profile/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
Labels: 💄 Design

#122 ✨[Feature/121]: 이 달의 추천 와인 수정
  src/components/about-wine/MonthlyWines.tsx
Labels: ✨Feature
